### ISSUE TITLE
Mobile optimizations

### ISSUE THREAD

**Issue by MrShoopa** [nspilman/juniordevstrugglebus#2]
There are a few issues on the website when being displayed on mobile devices:

- 'Upcoming Events' button missin
- First two menu items not truncated and 'moved' to the navigation menu
- Mobile navigation trigger button not working

An improvement which can be made on the websites functionality:
- Resize the 'MeetUp' logo and stylize it to a button

Other than that, website is looking great for a start :)

**Comment by nspilman** [comment]
Thanks MrShoopa! I can dig it. Mind making a pull request with the update?

**Comment by nspilman** [comment]
Hey Mr. Shoopa - The first 3 items are resolved. I've created a new issue for the Meetup logo resize. Closing this - thank you for the submission.

**Comment by MrShoopa** [comment]
Sounds good. :)

- Joe V.
